[package]
name = "adbselect"
version = "0.1.1"
edition = "2021"
authors = ["Kevin Most <kevin@kmost.com>"]
description = "Interactive ADB & Fastboot Device Selector & Shell Integration"
readme = "README.md"
repository = "https://github.com/kmost/adbselect"
license = "MIT"

[[bin]]
name = "adbs-bin"
path = "src/main.rs"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
